name: documentation

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install .[docs]
      - name: Install pandoc using apt
        run: sudo apt install pandoc
      - name: Convert the notebook examples to docs
        run: python docs/nb_examples_to_docs.py
      - name: Build documentation
        run: sphinx-build -b html docs dist/docs
